name: Deploy to github pages
on: 
    push:
        branches:
            - main 
jobs: 
    build-and-test-ci:
        uses: ./.github/workflows/ci.yml 
        with:
            upload-pages-artifact: true 
    deploy-to-pages: 
        runs-on: ubuntu-latest
        needs: build-and-test-ci 
        permissions:
            pages: write 
            id-token: write 
        environment: 
            name: github-pages 
            url: ${{ steps.deployment.outputs.page_url }}
        steps: 
            - uses: actions/configure-pages@v3 
            - uses: actions/deploy-pages@v2 
              id: deployment 




